#\uC560\uD50C\uB9AC\uCF00\uC774\uC158 \uD3EC\uD2B8 \uC124\uC815
#server.port=80

#MySQL \uC5F0\uACB0\uC124\uC815
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/article
    username: root
    password: 1111

    jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
          ddl-auto: create
      #MySQL \uBC29\uC5B8\uC124\uC815
      database-platform: org.hibernate.dialect.MySQLDialect

#\uCFFC\uB9AC\uC5D0 \uBB3C\uC74C\uD45C\uB85C \uCD9C\uB825\uB418\uB294 \uBC14\uC778\uB4DC \uD30C\uB77C\uBBF8\uD130 \uCD9C\uB825
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace