##\uC560\uD50C\uB9AC\uCF00\uC774\uC158 \uD3EC\uD2B8 \uC124\uC815
##server.port=80
#
##MySQL \uC5F0\uACB0\uC124\uC815
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/article
#spring.datasource.username=root
#spring.datasource.password=1111
#
##\uC2E4\uD589\uB418\uB294 \uCFFC\uB9AC \uCF58\uC194 \uCD9C\uB825
#spring.jpa.properties.hibernate.show_sql=true
#
##\uCF58\uC194\uC5D0 \uCD9C\uB825\uB418\uB294 \uCFFC\uB9AC\uB97C \uAC00\uB3C5\uC131 \uC788\uAC8C \uD3EC\uB9F7\uD305
#spring.jpa.properties.hibernate.format_sql=true
#
##\uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uCD08\uAE30\uD654 \uC804\uB7B5-
#spring.jpa.hibernate.ddl-auto=create
#
##\uCFFC\uB9AC\uC5D0 \uBB3C\uC74C\uD45C\uB85C \uCD9C\uB825\uB418\uB294 \uBC14\uC778\uB4DC \uD30C\uB77C\uBBF8\uD130 \uCD9C\uB825
#logging.level.org.hibernate.type.descriptor.sql=trace
#
##MySQL \uBC29\uC5B8\uC124\uC815-DB\uC5D0 \uB530\uB978 SQL \uAD6C\uBB38\uC758 \uCC28\uC774\uB97C \uD574\uACB0
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#\uC560\uD50C\uB9AC\uCF00\uC774\uC158 \uD3EC\uD2B8 \uC124\uC815
#server.port=80

#MySQL \uC5F0\uACB0\uC124\uC815
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/article
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

#\uCFFC\uB9AC\uC5D0 \uBB3C\uC74C\uD45C\uB85C \uCD9C\uB825\uB418\uB294 \uBC14\uC778\uB4DC \uD30C\uB77C\uBBF8\uD130 \uCD9C\uB825
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: trace